move to git sources as the build system seems to require a git checkout
The build is failing:

FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/syncthing-gtk --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/build/syncthing-gtk-1 --bind-mount=/run/build/syncthing-gtk=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/build/syncthing-gtk-1 --build-dir=/run/build/syncthing-gtk --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1682540845 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=SCCACHE_DIR=/run/ccache/sccache/ --env=RUSTC_WRAPPER=/app/bin/sccache --env=RUSTFLAGS=-g --env=RUST_BACKTRACE=1 --env=CARGO_NET_OFFLINE=true --env=CARGO_HOME=/run/build/python3-bcrypt/cargo --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/rust-stable/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=64 /srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/rofiles/rofiles-MBWXo5 /bin/sh -c 'pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "." --no-build-isolation'' on host
Using pip 23.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)
Looking in links: file:///run/build/syncthing-gtk
Processing /run/build/syncthing-gtk
  Running command python setup.py egg_info
  fatal: not a git repository (or any parent up to mount point /run/build)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  Traceback (most recent call last):
    File "/run/build/syncthing-gtk/setup.py", line 20, in get_version
      version = subprocess.check_output(["git", "describe", "--tags"])
    File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/run/build/syncthing-gtk/setup.py", line 105, in <module>
      version=get_version(),
    File "/run/build/syncthing-gtk/setup.py", line 29, in get_version
      raise RuntimeError(f'Directory name "{project_dir_name}" does not match "syncthing-gtk-<version>".')
  RuntimeError: Directory name "syncthing-gtk" does not match "syncthing-gtk-<version>".
  error: subprocess-exited-with-error