bump to python3
it seems as if the new version is not python2 compatible.
yay.
$ flatpak run --user me.kozec.syncthingtk//test
Traceback (most recent call last):
  File "/app/bin/syncthing-gtk", line 21, in <module>
    from syncthing_gtk.tools import init_logging, init_locale
File "/app/lib/python2.7/site-packages/syncthing_gtk/tools.py", line
129
    def get_header(headers: Dict[bytes, Any], key: bytes):
                          ^
SyntaxError: invalid syntax
$